apiVersion: v1
kind: ServiceAccount
metadata:
  name: risk-engine-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: risk-engine-pod-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: risk-engine-pod-manager-binding
subjects:
  - kind: ServiceAccount
    name: risk-engine-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: risk-engine-pod-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: adaptive-chaos-service-a:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: adaptive-chaos-service-b:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-engine
  template:
    metadata:
      labels:
        app: risk-engine
    spec:
      serviceAccountName: risk-engine-sa
      containers:
        - name: risk-engine
          image: adaptive-chaos-risk-engine:local
          imagePullPolicy: Never
          env:
            - name: PROMETHEUS_URL
              value: http://prometheus:9090
            - name: CHAOS_TARGET_LABEL
              value: app=service-a
            - name: CHECK_INTERVAL_MS
              value: "30000"
            - name: CHAOS_COOLDOWN_MS
              value: "90000"
            - name: W1
              value: "0.35"
            - name: W2
              value: "0.35"
            - name: W3
              value: "0.20"
            - name: W4
              value: "0.10"
          ports:
            - containerPort: 3002
